server:
  port: 5000
  
spring:
  application:
    name: ConfigServer
#================================
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AshwiniVtalent/Cloud_ConfigServer
#================================
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost